/*
Copyright (c) 2025 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import std.stdio;
import std.file;
import std.path;
import std.bitmanip;
import std.algorithm;
import std.array;

import dlib.core.memory;

import gscript;
import xtreme3d;

ubyte[] getEmbeddedBytecode(string exePath)
{
    auto f = File(exePath, "r");
    
    // Read signature
    f.seek(-8, SEEK_END);
    ubyte[8] embedSignatureBuffer;
    ubyte[] embedSignature = f.rawRead(embedSignatureBuffer);
    if (embedSignature[0..4] != "MAIN")
    {
        // Embed signature not found
        writeln("Embedded bytecode not found!");
        return [];
    }
    
    debug writefln("File size: %s byte(s)", f.size);

    // Read embed size
    debug writeln("Found embed signature");
    ubyte[4] emdedSizeData = embedSignature[4..$];
    uint emdedSize = littleEndianToNative!uint(emdedSizeData);
    debug writeln("Embed size: ", emdedSize);
    
    // Validate embed size
    if (emdedSize == 0 || emdedSize > f.size - 8)
    {
        writeln("Invalid embedded bytecode size!");
        return [];
    }
    
    // Read embedded bytecode
    int embedOffset = -8 - cast(int)emdedSize;
    debug writeln("Seek to ", embedOffset);
    f.seek(embedOffset, SEEK_END);
    debug writeln("Position after seek: ", f.tell);
    ubyte[] code = new ubyte[emdedSize];
    ubyte[] readCode = f.rawRead(code);
    debug writefln("Read %s byte(s)", readCode.length);
    if (readCode.length != code.length) {
        writeln("Failed to read embedded bytecode!");
        return [];
    }
    
    return readCode;
}

void main(string[] args)
{
    x3dInit();
    string exePath = thisExePath();
    
    ubyte[] code = getEmbeddedBytecode(exePath);
    if (code.length == 0)
        return;
    
    GsInstruction[] instructions = loadBytecode(code);
    if (instructions.length == 0)
    {
        writeln("No bytecode to run");
        return;
    }
    
    auto vm = New!GsVirtualMachine();
    GsDynamic[] vmArgs = args.map!(s => GsDynamic(s)).array;
    vm.set("args", GsDynamic(vmArgs));
    x3dBindFunctions(vm);
    vm.load(instructions);
    vm.run();
    Delete(vm);
}
