/*
Copyright (c) 2025 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module gscript.assembler;

import std.stdio;
import std.conv;
import std.algorithm;
import std.array;
import std.string;

import gscript.instructions;
import gscript.dynamic;

class GsAssembler
{
    private string[] lines;

    this(string source)
    {
        this.lines = source.splitLines();
    }

    GsInstruction[] assemble()
    {
        GsInstruction[] instructions;
        
        foreach (line; lines)
        {
            line = line.strip();
            if (line.empty || line.startsWith("//")) continue;

            foreach (statement; line.split(";"))
            {
                statement = statement.strip();
                if (statement.empty) continue;
                if (statement.endsWith(":")) // Label definition
                {
                    string label = statement[0..$-1]; // Remove the colon
                    instructions ~= GsInstruction(GsInstructionType.LABEL, GsDynamic(label));
                }
                else
                {
                    auto parts = statement.split();
                    auto mnemonic = parts[0];
                    auto operandStr = parts.length > 1 ? parts[1..$].join(" ") : null;
                    GsDynamic operand;
                    if (operandStr.length)
                        operand = parseOperand(operandStr);
                    instructions ~= parseInstruction(mnemonic, operand);
                }
            }
        }
        
        if (instructions[$-1].type != GsInstructionType.HALT)
            instructions ~= GsInstruction(GsInstructionType.HALT);

        return instructions;
    }

    private GsInstruction parseInstruction(string mnemonic, GsDynamic operand)
    {
        GsInstruction result;
        switch(mnemonic.toUpper())
        {
            case "PUSH":
                result = GsInstruction(GsInstructionType.PUSH, operand);
                break;
            case "POP":
                result = GsInstruction(GsInstructionType.POP);
                break;
            case "ADD":
                result = GsInstruction(GsInstructionType.ADD);
                break;
            case "SUB":
                result = GsInstruction(GsInstructionType.SUB);
                break;
            case "MUL":
                result = GsInstruction(GsInstructionType.MUL);
                break;
            case "DIV":
                result = GsInstruction(GsInstructionType.DIV);
                break;
            case "MOD":
                result = GsInstruction(GsInstructionType.MOD);
                break;
            case "AND":
                result = GsInstruction(GsInstructionType.AND);
                break;
            case "OR":
                result = GsInstruction(GsInstructionType.OR);
                break;
            case "NOT":
                result = GsInstruction(GsInstructionType.NOT);
                break;
            case "CAT":
                result = GsInstruction(GsInstructionType.CAT);
                break;
            case "LESS":
                result = GsInstruction(GsInstructionType.LESS);
                break;
            case "GREATER":
                result = GsInstruction(GsInstructionType.GREATER);
                break;
            case "LESS_EQ":
                result = GsInstruction(GsInstructionType.LESS_EQ);
                break;
            case "GREATER_EQ":
                result = GsInstruction(GsInstructionType.GREATER_EQ);
                break;
            case "EQ":
                result = GsInstruction(GsInstructionType.EQ);
                break;
            case "NEQ":
                result = GsInstruction(GsInstructionType.EQ);
                break;
            case "JMP":
                result = GsInstruction(GsInstructionType.JMP, operand);
                break;
            case "JMP_IF":
                result = GsInstruction(GsInstructionType.JMP_IF, operand);
                break;
            case "JMP_IF_NOT":
                result = GsInstruction(GsInstructionType.JMP_IF_NOT, operand);
                break;
            case "INDEX_GET":
                result = GsInstruction(GsInstructionType.INDEX_GET);
                break;
            case "INDEX_SET":
                result = GsInstruction(GsInstructionType.INDEX_SET);
                break;
            case "LENGTH":
                result = GsInstruction(GsInstructionType.LENGTH);
                break;
            case "PRINT":
                result = GsInstruction(GsInstructionType.PRINT);
                break;
            case "HALT":
                result = GsInstruction(GsInstructionType.HALT);
                break;
            case "CALL":
                result = GsInstruction(GsInstructionType.CALL, operand);
                break;
            case "RET":
                result = GsInstruction(GsInstructionType.RET);
                break;
            case "LOAD_VAR":
                result = GsInstruction(GsInstructionType.LOAD_VAR, operand);
                break;
            case "STORE_VAR":
                result = GsInstruction(GsInstructionType.STORE_VAR, operand);
                break;
            case "LOAD_ARG":
                result = GsInstruction(GsInstructionType.LOAD_ARG, operand);
                break;
            case "STORE_ARG":
                result = GsInstruction(GsInstructionType.STORE_ARG, operand);
                break;
            case "NEW":
                result = GsInstruction(GsInstructionType.NEW);
                break;
            case "GET":
                result = GsInstruction(GsInstructionType.GET, operand);
                break;
            case "SET":
                result = GsInstruction(GsInstructionType.SET, operand);
                break;
            case "CONTAINS":
                result = GsInstruction(GsInstructionType.CONTAINS, operand);
                break;
            case "GLOBAL":
                result = GsInstruction(GsInstructionType.GLOBAL);
                break;
            case "ARRAY":
                result = GsInstruction(GsInstructionType.ARRAY);
                break;
            case "GLOBAL_LOAD_VAR":
                result = GsInstruction(GsInstructionType.GLOBAL_LOAD_VAR);
                break;
            case "GLOBAL_STORE_VAR":
                result = GsInstruction(GsInstructionType.GLOBAL_STORE_VAR);
                break;
            case "INIT_SET":
                result = GsInstruction(GsInstructionType.INIT_SET, operand);
                break;
            case "REUSE":
                result = GsInstruction(GsInstructionType.REUSE);
                break;
            case "LOAD_ARGS":
                result = GsInstruction(GsInstructionType.LOAD_ARGS);
                break;
            default:
                throw new Exception("Unknown instruction: " ~ mnemonic);
        }
        return result;
    }

    private GsDynamic parseOperand(string operand)
    {
        if (operand.startsWith("\"") && operand.endsWith("\""))
        {
            return GsDynamic(operand[1 .. $-1]); // String literal
        }
        else if (operand == "true" || operand == "false")
        {
            return GsDynamic(to!bool(operand)); // Boolean
        }
        else if (operand.canFind("."))
        {
            return GsDynamic(to!double(operand)); // Floating-point number
        }
        else if (operand.canFind("0x"))
        {
            return GsDynamic(cast(double)to!int(operand, 16)); // Hexadecimal integer
        }
        else
        {
            return GsDynamic(cast(double)to!int(operand)); // Integer
        }
    }
}

GsInstruction[] assemble(string program)
{
    auto assembler = new GsAssembler(program);
    GsInstruction[] instructions = assembler.assemble();
    return instructions;
}
