/*
Copyright (c) 2025 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module gscript.compiler;

import std.stdio;
import std.file;
import std.path;

import gscript.lexer;
import gscript.parser;
import gscript.codegen;
import gscript.instructions;

bool parseModule(GsProgram program, GsModule modul, string script, string filename, string importDirectory)
{
    if (!modul.ready)
    {
        GsLexer lexer = new GsLexer(script);
        GsParser parser = new GsParser(lexer, filename);
        if (parser.parseModule(program, modul))
        {
            modul.ready = true;
            bool res = true;
            foreach(importFilename; modul.imports)
            {
                if (!program.isModuleImported(importFilename))
                {
                    GsModule newModul = program.importModule(importFilename);
                    if (!newModul.ready)
                    {
                        string importScript = readText(buildPath(importDirectory, importFilename));
                        res = parseModule(program, newModul, importScript, importFilename, importDirectory);
                        if (!res)
                            break;
                    }
                }
            }
            
            return res;
        }
        else
        {
            modul.ready = true;
            return false;
        }
    }
    else
        return true;
}

GsInstruction[] compile(string script, string moduleFilename = "")
{
    GsProgram program = new GsProgram(moduleFilename);
    GsModule mainModule = program.mainModule;
    
    GsLexer lexer = new GsLexer(script);
    GsParser parser = new GsParser(lexer, moduleFilename);
    if (parser.parseModule(program, mainModule))
    {
        mainModule.ready = true;
        
        // TODO: user-defined import paths
        string importDirectory = "";
        if (moduleFilename.length > 0)
        {
            importDirectory = dirName(moduleFilename);
        }
        
        bool res = true;
        
        foreach(importFilename; mainModule.imports)
        {
            program.importModule(importFilename);
        }
        
        foreach(importFilename; mainModule.imports)
        {
            GsModule modul = program.importModule(importFilename);
            if (!modul.ready)
            {
                string importScript = readText(buildPath(importDirectory, importFilename));
                res = parseModule(program, modul, importScript, importFilename, importDirectory);
                if (!res)
                    break;
            }
        }
        
        if (!res)
            return[];
        
        GsCodeGenerator cg = new GsCodeGenerator();
        
        debug
        {
            foreach(m; program.modulesInImportOrder)
            {
                writeln(m.filename, ":");
                foreach(ASTNode node; m.ast)
                    node.print("  ");
            }
        }
        
        GsInstruction[] instr = cg.generate(program);
        
        return instr;
    }
    else
        return [];
}
