/*
Copyright (c) 2025 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module gscript.labelmap;

class LabelMap
{
    private struct Entry
    {
        string key;
        size_t value;
        bool used;
        bool filled;
    }

    private Entry[] table;
    private size_t count;
    private size_t mask;

    this(size_t capacity)
    {
        size_t cap = 1;
        while (cap < capacity * 2) cap <<= 1;
        table = new Entry[cap];
        mask = cap - 1;
    }

    private size_t hash(string s) const
    {
        ulong h = 1469598103934665603UL;
        foreach (ubyte c; s) {
            h ^= c;
            h *= 1099511628211UL;
        }
        return cast(size_t)h;
    }

    void add(string key, size_t value)
    {
        if (count * 2 >= table.length) rehash();
        insert(key, value);
    }

    private void insert(string key, size_t value)
    {
        size_t i = hash(key) & mask;
        while (table[i].filled)
        {
            if (table[i].key == key)
            {
                table[i].value = value;
                return;
            }
            i = (i + 1) & mask;
        }
        table[i] = Entry(key, value, true, true);
        count++;
    }

    bool remove(string key)
    {
        size_t i = hash(key) & mask;
        while (table[i].used)
        {
            if (table[i].filled && table[i].key == key)
            {
                table[i].filled = false;
                count--;
                return true;
            }
            i = (i + 1) & mask;
        }
        return false;
    }

    size_t* opBinaryRight(string op: "in")(string key)
    {
        size_t i = hash(key) & mask;
        while (table[i].used) {
            if (table[i].filled && table[i].key == key)
                return &table[i].value;
            i = (i + 1) & mask;
        }
        return null;
    }

    size_t opIndex(string key)
    {
        auto p = key in this;
        //if (!p) throw new Exception("Key not found: "~key);
        return *p;
    }
    
    size_t opIndexAssign(size_t v, string k)
    {
        add(k, v);
        return v;
    }

    private void rehash()
    {
        auto old = table;
        size_t cap = table.length * 2;
        table.length = cap;
        foreach (ref e; table) e = Entry.init;
        mask = cap - 1;
        count = 0;
        foreach (ref e; old)
        {
            if (e.filled)
                insert(e.key, e.value);
        }
    }
}
